// Define action types
export const SET_EMPLOYEE_DATA = 'SET_EMPLOYEE_DATA';
export const SET_EMPLOYEE_PROFILE_PHOTO = 'SET_EMPLOYEE_PROFILE_PHOTO';
export const SET_EMPLOYEE_NAME = 'SET_EMPLOYEE_NAME';
export const SET_EMPLOYEE_OTHER_INFO = 'SET_EMPLOYEE_OTHER_INFO';
export const SET_EMPLOYEE_USERNAME = 'SET_EMPLOYEE_USERNAME';
export const SET_EMPLOYEE_EMAIL = 'SET_EMPLOYEE_EMAIL';
export const SET_EMPLOYEE_FIRSTNAME = 'SET_EMPLOYEE_FIRSTNAME';
export const SET_EMPLOYEE_LASTNAME = 'SET_EMPLOYEE_LASTNAME';
export const SET_EMPLOYEE_DOB = 'SET_EMPLOYEE_DOB';
export const SET_EMPLOYEE_MOBILE = 'SET_EMPLOYEE_MOBILE';
export const SET_EMPLOYEE_GENDER = 'SET_EMPLOYEE_GENDER';
export const SET_EMPLOYEE_JOB_DESCRIPTION = 'SET_EMPLOYEE_JOB_DESCRIPTION';
export const SET_EMPLOYEE_SKILLS = 'SET_EMPLOYEE_SKILLS';
// Add more action types as needed
